@if (is_plugin_active('newsletter'))
    @switch($sidebar)
        @case('footer_sidebar')
            @include(Theme::getThemeNamespace('widgets.newsletter.sidebars.templates.partials.footer'))
            @break
        @case('blog_bottom_sidebar')
            @include(Theme::getThemeNamespace('widgets.newsletter.sidebars.templates.partials.blog-bottom'))
            @break
        @case('menu')
            @include(Theme::getThemeNamespace('widgets.newsletter.sidebars.templates.partials.menu'))
            @break
        @case('custom_sidebar_1')
            @include(Theme::getThemeNamespace('widgets.newsletter.sidebars.templates.partials.primary'))
            @break
        @case('primary')
            @include(Theme::getThemeNamespace('widgets.newsletter.sidebars.templates.partials.primary'))
            @break
        @case('above_footer_sidebar')
            @include(Theme::getThemeNamespace('widgets.newsletter.sidebars.templates.partials.above-footer'))
            @break
    @endswitch
@endif
